name: base64_image_picker
description: "simplifies the process of selecting, converting and integrating images into Flutter applications enhancing both developer productivity and user satisfaction"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: 'Package Demo'
    path: asset/base64_image_picker.gif